name: Delete Preview CI

on:
  pull_request:
    types: [closed]

jobs:
  delete_preview:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Surge Down
        env:
          PROJECT_NAME: 'yc-tw-theme'
          BRANCH_NAME: ${{ github.ref }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        shell: bash
        run: |
          npm run preview:down
          printf "-> %o" "${{github.event.pull_request}}"

      - run: |
          echo Preview application #${{ github.event.number }} has been deleted
